import AuvoService from './auvoApiRequests.ts';
import usersMod from '../models/usersMod.ts';
import { User } from '../utils/auvoInterfaces.ts';

const userList: User[] = await AuvoService.requestListComplete('Users');

const userList2 = [
  {
    userID: 179747,
    externalId: '',
    name: 'Ueder Pereira de Souza Alves',
    smartPhoneNumber: '',
    login: 'ueder.pereira',
    email: '',
    culture: 'pt-BR',
    jobPosition: 'Tecnico de Instalação',
    userType: { userTypeId: 1, description: 'User' },
    address: 'Barreiras, BA, Brasil',
    latitude: -12.14764,
    longitude: -44.9949,
    workDaysOfWeek: [1, 2, 3, 4, 5, 6, 7],
    startWorkHour: '08:00:00',
    endWorkHour: '18:00:00',
    startLunchHour: '12:00:00',
    endLunchHour: '14:00:00',
    hourValue: 0,
    pictureUrl: '',
    basePoint: {
      address: 'Barreiras, BA, Brasil',
      latitude: -12.14764,
      longitude: -44.9949,
    },
    openTaskInPlace: false,
    grabGalleryPhotos: true,
    gpsFrequency: 300,
    checkInManual: true,
    unavailableForTasks: false,
    editTaskAfterCheckout: true,
    informStartTravel: true,
    changeBasePoint: true,
    registrationDate: '2024-11-13T15:59:47',
    monitoringNotification: { gpsActivation: 0, gpsDisabling: 0, appLogin: 0, appLogout: 0 },
    employeeNotification: { basePointChange: 0 },
    clientNotification: { adressChange: 0 },
    taskNotification: {
      checkIn: 0,
      checkout: 0,
      rescheduling: 0,
      travelStart: 0,
      researchAnswer: 0,
      delay: 0,
      taskDelete: 0,
    },
  },
  {
    userID: 139816,
    externalId: '',
    name: 'Valdieres Mendes dos Santos',
    smartPhoneNumber: '',
    login: 'valdieres.mendes',
    email: '',
    culture: 'pt-BR',
    jobPosition: 'Tecnico de Instalação e Manutenção',
    userType: { userTypeId: 1, description: 'User' },
    address: 'Porto Seguro, Porto Seguro-BA, 45810-000',
    latitude: -16.45097,
    longitude: -39.06462,
    workDaysOfWeek: [1, 2, 3, 4, 5, 6, 7],
    startWorkHour: '08:00:00',
    endWorkHour: '18:00:00',
    startLunchHour: '12:00:00',
    endLunchHour: '14:00:00',
    hourValue: 14.8,
    pictureUrl: '',
    basePoint: {
      address: 'Porto Seguro, Porto Seguro-BA, 45810-000',
      latitude: -16.45097,
      longitude: -39.06462,
    },
    openTaskInPlace: false,
    grabGalleryPhotos: true,
    gpsFrequency: 60,
    checkInManual: true,
    unavailableForTasks: false,
    editTaskAfterCheckout: true,
    informStartTravel: true,
    changeBasePoint: false,
    registrationDate: '2023-06-30T16:38:33',
    monitoringNotification: { gpsActivation: 0, gpsDisabling: 0, appLogin: 0, appLogout: 0 },
    employeeNotification: { basePointChange: 0 },
    clientNotification: { adressChange: 0 },
    taskNotification: {
      checkIn: 0,
      checkout: 0,
      rescheduling: 0,
      travelStart: 0,
      researchAnswer: 0,
      delay: 0,
      taskDelete: 0,
    },
  },
];
